# Samsung SDM450 Project

dtb-$(CONFIG_MACH_A6PLTE_EUR_OPEN) += sdm450-sec-a6plte_eur_open-r00.dtb \
					sdm450-sec-a6plte_eur_open-r01.dtb \
					sdm450-sec-a6plte_eur_open-r02.dtb \
					sdm450-sec-a6plte_eur_open-r03.dtb \
					sdm450-sec-a6plte_eur_open-r04.dtb
					
dtb-$(CONFIG_MACH_A6PLTE_MEA_OPEN) += sdm450-sec-a6plte_mea_open-r00.dtb \
					sdm450-sec-a6plte_mea_open-r01.dtb \
					sdm450-sec-a6plte_mea_open-r02.dtb \
					sdm450-sec-a6plte_mea_open-r03.dtb \
					sdm450-sec-a6plte_mea_open-r04.dtb

dtb-$(CONFIG_MACH_A6PLTE_SEA_OPEN) += sdm450-sec-a6plte_eur_open-r00.dtb \
					sdm450-sec-a6plte_eur_open-r01.dtb \
					sdm450-sec-a6plte_eur_open-r02.dtb \
					sdm450-sec-a6plte_eur_open-r03.dtb \
					sdm450-sec-a6plte_eur_open-r04.dtb		
					
dtb-$(CONFIG_MACH_A6PLTE_LTN_OPEN) += sdm450-sec-a6plte_ltn_open-r03.dtb \
                                        sdm450-sec-a6plte_ltn_open-r04.dtb

dtb-$(CONFIG_MACH_A6PLTE_CHN_OPEN) += sdm450-sec-a6plte_chn_open-r00.dtb \
					sdm450-sec-a6plte_chn_open-r01.dtb \
					sdm450-sec-a6plte_chn_open-r02.dtb \
					sdm450-sec-a6plte_chn_open-r03.dtb \
					sdm450-sec-a6plte_chn_open-r04.dtb

dtb-$(CONFIG_MACH_A6PLTE_KOR_KTT) += sdm450-sec-a6plte_kor_ktt-r00.dtb \
					sdm450-sec-a6plte_kor_ktt-r01.dtb \
					sdm450-sec-a6plte_kor_ktt-r02.dtb \
					sdm450-sec-a6plte_kor_ktt-r03.dtb \
					sdm450-sec-a6plte_kor_ktt-r04.dtb

dtb-$(CONFIG_MACH_A6PLTE_CIS_SER) += sdm450-sec-a6plte_cis_ser-r00.dtb \
					sdm450-sec-a6plte_cis_ser-r01.dtb \
					sdm450-sec-a6plte_cis_ser-r02.dtb \
					sdm450-sec-a6plte_cis_ser-r03.dtb \
					sdm450-sec-a6plte_cis_ser-r04.dtb


dtb-$(CONFIG_MACH_GTA2XLLTE_EUR_OPEN) += sdm450-sec-gta2xllte_eur_open-r00.dtb \
					sdm450-sec-gta2xllte_eur_open-r01.dtb \
					sdm450-sec-gta2xllte_eur_open-r02.dtb \
					sdm450-sec-gta2xllte_eur_open-r03.dtb \
					sdm450-sec-gta2xllte_eur_open-r04.dtb \
					sdm450-sec-gta2xllte_eur_open-r05.dtb

dtb-$(CONFIG_MACH_GTA2XLLTE_USA_SPR) += sdm450-sec-gta2xllte_usa_spr-r00.dtb \
					sdm450-sec-gta2xllte_usa_spr-r01.dtb \
					sdm450-sec-gta2xllte_usa_spr-r02.dtb \
					sdm450-sec-gta2xllte_usa_spr-r03.dtb \
					sdm450-sec-gta2xllte_usa_spr-r04.dtb \
					sdm450-sec-gta2xllte_usa_spr-r05.dtb

dtb-$(CONFIG_MACH_GTA2XLLTE_USA_VZW) += sdm450-sec-gta2xllte_usa_vzw-r00.dtb \
					sdm450-sec-gta2xllte_usa_vzw-r01.dtb \
					sdm450-sec-gta2xllte_usa_vzw-r02.dtb \
					sdm450-sec-gta2xllte_usa_vzw-r03.dtb \
					sdm450-sec-gta2xllte_usa_vzw-r04.dtb \
					sdm450-sec-gta2xllte_usa_vzw-r05.dtb

dtb-$(CONFIG_MACH_GTA2XLLTE_MEA_OPEN) += sdm450-sec-gta2xllte_mea_open-r00.dtb \
					sdm450-sec-gta2xllte_mea_open-r01.dtb \
					sdm450-sec-gta2xllte_mea_open-r02.dtb \
					sdm450-sec-gta2xllte_mea_open-r03.dtb \
					sdm450-sec-gta2xllte_mea_open-r04.dtb \
					sdm450-sec-gta2xllte_mea_open-r05.dtb
					
dtb-$(CONFIG_MACH_GTA2XLLTE_MEA_TUR) += sdm450-sec-gta2xllte_mea_tur-r00.dtb \
					sdm450-sec-gta2xllte_mea_tur-r01.dtb \
					sdm450-sec-gta2xllte_mea_tur-r02.dtb \
					sdm450-sec-gta2xllte_mea_tur-r03.dtb \
					sdm450-sec-gta2xllte_mea_tur-r04.dtb \
					sdm450-sec-gta2xllte_mea_tur-r05.dtb

dtb-$(CONFIG_MACH_GTA2XLWIFI_EUR_OPEN) += sdm450-sec-gta2xlwifi_eur_open-r02.dtb \
					sda450-sec-gta2xlwifi_eur_open-r02.dtb \
					sda450-sec-gta2xlwifi_eur_open-r03.dtb \
					sda450-sec-gta2xlwifi_eur_open-r04.dtb \
					sda450-sec-gta2xlwifi_eur_open-r05.dtb

dtb-$(CONFIG_MACH_J6PLTE_CIS_SER) += sdm450-sec-j6plte_cis_ser-r00.dtb \
					sdm450-sec-j6plte_cis_ser-r01.dtb \
					sdm450-sec-j6plte_cis_ser-r02.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)

clean-files := *.dtb *.reserve.dts
